"""initial schema

Revision ID: 1f9abb431f51
Revises: 
Create Date: 2026-08-27 22:22:01.298975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f9abb431f51'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cnaes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cnaes_code'), 'cnaes', ['code'], unique=True)
    op.create_table('empresas_staging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj_basico', sa.String(length=8), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=True),
    sa.Column('porte_empresa', sa.String(length=2), nullable=True),
    sa.Column('source_file', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj_basico', name='uq_empresas_staging_cnpj_basico')
    )
    op.create_table('estabelecimentos_staging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj_basico', sa.String(length=8), nullable=False),
    sa.Column('cnpj_ordem', sa.String(length=4), nullable=False),
    sa.Column('cnpj_dv', sa.String(length=2), nullable=False),
    sa.Column('identificador_matriz_filial', sa.String(length=1), nullable=True),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('situacao_cadastral', sa.String(length=2), nullable=True),
    sa.Column('data_inicio_atividade', sa.Date(), nullable=True),
    sa.Column('cnae_fiscal_principal', sa.String(length=16), nullable=True),
    sa.Column('cnae_fiscal_secundaria', sa.String(length=2048), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('municipio_codigo', sa.String(length=16), nullable=True),
    sa.Column('ddd_1', sa.String(length=4), nullable=True),
    sa.Column('telefone_1', sa.String(length=32), nullable=True),
    sa.Column('correio_eletronico', sa.String(length=120), nullable=True),
    sa.Column('source_file', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj_basico', 'cnpj_ordem', 'cnpj_dv', name='uq_estabelecimentos_staging_cnpj')
    )
    op.create_index(op.f('ix_estabelecimentos_staging_situacao_cadastral'), 'estabelecimentos_staging', ['situacao_cadastral'], unique=False)
    op.create_table('import_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('filename', sa.String(length=60), nullable=False),
    sa.Column('rows_imported', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period', 'filename', name='uq_import_log_period_filename')
    )
    op.create_table('import_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('group', sa.String(length=20), nullable=True),
    sa.Column('current_file', sa.String(length=60), nullable=True),
    sa.Column('step', sa.String(length=20), nullable=True),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receita_code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_municipios_receita_code'), 'municipios', ['receita_code'], unique=True)
    op.create_table('simples_staging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj_basico', sa.String(length=8), nullable=False),
    sa.Column('opcao_simples', sa.String(length=1), nullable=True),
    sa.Column('opcao_mei', sa.String(length=1), nullable=True),
    sa.Column('source_file', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj_basico', name='uq_simples_staging_cnpj_basico')
    )
    op.create_table('establishments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('is_headquarters', sa.Boolean(), nullable=False),
    sa.Column('is_mei', sa.Boolean(), nullable=False),
    sa.Column('is_simples', sa.Boolean(), nullable=False),
    sa.Column('company_size', sa.String(length=2), nullable=True),
    sa.Column('main_cnae_code', sa.String(length=16), nullable=True),
    sa.Column('secondary_cnae_codes', sa.JSON(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('cellphone', sa.String(length=32), nullable=True),
    sa.Column('cellphone_confidence', sa.SmallInteger(), nullable=False),
    sa.Column('opened_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_establishments_cellphone'), 'establishments', ['cellphone'], unique=False)
    op.create_index(op.f('ix_establishments_cnpj'), 'establishments', ['cnpj'], unique=True)
    op.create_index(op.f('ix_establishments_main_cnae_code'), 'establishments', ['main_cnae_code'], unique=False)
    op.create_index(op.f('ix_establishments_uf'), 'establishments', ['uf'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_establishments_uf'), table_name='establishments')
    op.drop_index(op.f('ix_establishments_main_cnae_code'), table_name='establishments')
    op.drop_index(op.f('ix_establishments_cnpj'), table_name='establishments')
    op.drop_index(op.f('ix_establishments_cellphone'), table_name='establishments')
    op.drop_table('establishments')
    op.drop_table('simples_staging')
    op.drop_index(op.f('ix_municipios_receita_code'), table_name='municipios')
    op.drop_table('municipios')
    op.drop_table('import_progress')
    op.drop_table('import_log')
    op.drop_index(op.f('ix_estabelecimentos_staging_situacao_cadastral'), table_name='estabelecimentos_staging')
    op.drop_table('estabelecimentos_staging')
    op.drop_table('empresas_staging')
    op.drop_index(op.f('ix_cnaes_code'), table_name='cnaes')
    op.drop_table('cnaes')
    # ### end Alembic commands ###
