"""add municipio latitude/longitude for geo fallback

Revision ID: 7a6d0dfd18cb
Revises: c076b6b91515
Create Date: 2026-08-28 16:41:37.781485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a6d0dfd18cb'
down_revision: Union[str, Sequence[str], None] = 'c076b6b91515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('municipios', sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('municipios', sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('municipios', 'longitude')
    op.drop_column('municipios', 'latitude')
    # ### end Alembic commands ###
