"""add reference tables (naturezas, qualificacoes, paises, motivos), socios, cep coordenadas, ibge municipio fields, and full situacao cadastral

Revision ID: ae61be96739d
Revises: cfa92967b3ec
Create Date: 2026-08-28 14:23:34.517430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae61be96739d'
down_revision: Union[str, Sequence[str], None] = 'cfa92967b3ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cep_coordenadas',
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cep')
    )
    op.create_table('motivos_situacao_cadastral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motivos_situacao_cadastral_code'), 'motivos_situacao_cadastral', ['code'], unique=True)
    op.create_table('naturezas_juridicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_naturezas_juridicas_code'), 'naturezas_juridicas', ['code'], unique=True)
    op.create_table('paises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paises_code'), 'paises', ['code'], unique=True)
    op.create_table('qualificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualificacoes_code'), 'qualificacoes', ['code'], unique=True)
    op.create_table('socios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj_basico', sa.String(length=8), nullable=False),
    sa.Column('identificador_socio', sa.String(length=1), nullable=True),
    sa.Column('nome_socio', sa.String(length=255), nullable=False),
    sa.Column('cpf_cnpj_socio', sa.String(length=14), nullable=True),
    sa.Column('qualificacao_socio', sa.String(length=8), nullable=True),
    sa.Column('data_entrada_sociedade', sa.Date(), nullable=True),
    sa.Column('pais', sa.String(length=8), nullable=True),
    sa.Column('representante_legal', sa.String(length=14), nullable=True),
    sa.Column('nome_representante', sa.String(length=255), nullable=True),
    sa.Column('qualificacao_representante_legal', sa.String(length=8), nullable=True),
    sa.Column('faixa_etaria', sa.String(length=1), nullable=True),
    sa.Column('source_file', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_socios_cnpj_basico'), 'socios', ['cnpj_basico'], unique=False)
    op.create_index(op.f('ix_socios_cpf_cnpj_socio'), 'socios', ['cpf_cnpj_socio'], unique=False)
    op.add_column('empresas_staging', sa.Column('natureza_juridica', sa.String(length=8), nullable=True))
    op.add_column('estabelecimentos_staging', sa.Column('motivo_situacao_cadastral', sa.String(length=8), nullable=True))
    op.add_column('establishments', sa.Column('natureza_juridica_code', sa.String(length=8), nullable=True))
    op.add_column('establishments', sa.Column('situacao_cadastral', sa.String(length=2), nullable=True))
    op.add_column('establishments', sa.Column('motivo_situacao_cadastral_code', sa.String(length=8), nullable=True))
    op.create_index(op.f('ix_establishments_situacao_cadastral'), 'establishments', ['situacao_cadastral'], unique=False)
    op.add_column('municipios', sa.Column('ibge_code', sa.String(length=7), nullable=True))
    op.add_column('municipios', sa.Column('population', sa.BigInteger(), nullable=True))
    op.add_column('municipios', sa.Column('area_km2', sa.Numeric(precision=12, scale=3), nullable=True))
    op.create_index(op.f('ix_municipios_ibge_code'), 'municipios', ['ibge_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_municipios_ibge_code'), table_name='municipios')
    op.drop_column('municipios', 'area_km2')
    op.drop_column('municipios', 'population')
    op.drop_column('municipios', 'ibge_code')
    op.drop_index(op.f('ix_establishments_situacao_cadastral'), table_name='establishments')
    op.drop_column('establishments', 'motivo_situacao_cadastral_code')
    op.drop_column('establishments', 'situacao_cadastral')
    op.drop_column('establishments', 'natureza_juridica_code')
    op.drop_column('estabelecimentos_staging', 'motivo_situacao_cadastral')
    op.drop_column('empresas_staging', 'natureza_juridica')
    op.drop_index(op.f('ix_socios_cpf_cnpj_socio'), table_name='socios')
    op.drop_index(op.f('ix_socios_cnpj_basico'), table_name='socios')
    op.drop_table('socios')
    op.drop_index(op.f('ix_qualificacoes_code'), table_name='qualificacoes')
    op.drop_table('qualificacoes')
    op.drop_index(op.f('ix_paises_code'), table_name='paises')
    op.drop_table('paises')
    op.drop_index(op.f('ix_naturezas_juridicas_code'), table_name='naturezas_juridicas')
    op.drop_table('naturezas_juridicas')
    op.drop_index(op.f('ix_motivos_situacao_cadastral_code'), table_name='motivos_situacao_cadastral')
    op.drop_table('motivos_situacao_cadastral')
    op.drop_table('cep_coordenadas')
    # ### end Alembic commands ###
