"""drop unused index on estabelecimentos_staging.situacao_cadastral

Revision ID: d5821abae220
Revises: 1f9abb431f51
Create Date: 2026-08-28 12:28:50.502050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5821abae220'
down_revision: Union[str, Sequence[str], None] = '1f9abb431f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_estabelecimentos_staging_situacao_cadastral', table_name='estabelecimentos_staging')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_estabelecimentos_staging_situacao_cadastral', 'estabelecimentos_staging', ['situacao_cadastral'], unique=False)
    # ### end Alembic commands ###
